name: Update Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # - name: Install dependencies
        # run: |
        #   python -m pip install --upgrade pip
        #   pip install -r requirements.txt

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Get tag name
        id: tag
        run: echo ${{ github.ref }}

      - name: Get release ID
        id: release
        uses: SoftInstigate/rest-api-consumer@v1
        with:
          url: https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.tag.outputs.tag_name }}
          method: GET
          headers: |
            Accept: application/vnd.github.v3+json
            Authorization: token ${{ secrets.GITHUB_TOKEN }}
        if: steps.tag.outputs.tag_name != 'main'

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./sum-tripper.zip
          asset_name: sum-tripper-${{ github.sha }}.tar.gz
          asset_content_type: application/gzip
          asset_label: sum-tripper-${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.tag.outputs.tag_name != 'main'
